development:
  name: discuss
  url: http://dev.2010.mindpin.com/
  master_url: http://dev.2010.mindpin.com/

test:
  name: discuss
  url: http://dev.2010.mindpin.com/
  master_url: http://dev.2010.mindpin.com/

production:
  name: discuss
  url: http://2010.mindpin.com/
  master_url: http://2010.mindpin.com/