development:
  name: discuss
  url: http://dev.discuss.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/

test:
  name: discuss
  url: http://dev.discuss.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/

production:
  name: discuss
  url: http://discuss.2010.mindpin.com/
  master_url: http://config-manager.2010.mindpin.com/
